name: Automation Tests

on:
  push:
    branches:
      - dev  # Adjust this to your main branch name

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14  # Adjust this to your Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
