name: Automation Tests

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20  

      - name: Install dependencies
        run: npm install

      - name: Run tests with Jest
        run: npm test -- --coverage  # Add --coverage to generate test coverage report

      - name: Upload Jest Test Reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: jest-test-reports
          path: coverage  # Specify the path where Jest stores coverage reports
